version = 0.1
[sandbox]
[sandbox.deploy]
[sandbox.deploy.parameters]
stack_name = "sandbox-sam-reference-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-w065kzffb99e"
s3_prefix = "sandbox-sam-reference-app"
region = "eu-central-1"
profile = "e-sandbox"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Stage=\"sandbox\""

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "dev-sam-reference-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5dyv0ffcs99x"
s3_prefix = "dev-sam-reference-app"
region = "eu-west-1"
profile = "default"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Stage=\"dev\""
